### ISSUE TITLE
`endsWith('abc', 'f')` returns `true`

### ISSUE THREAD

**Issue by joelnet** [vanillajs2/absurdum#33]
`endsWith('abc', 'f')` returns `true`

## Environment

- Platform: Node
- Version: 10.15.3
- Operator: Ubuntu

## Steps to reproduce

- call function endsWith with arguments 'abc', and 'f'

## Expected behaviour

should return `false`

## Actual behaviour

returns `true`

## Code

Seems like code could be replaced with:

```javascript
const endsWith = (string, substr = '') =>
  string.substr(string.length - substr.length) === substr
```

**Comment by evanplaice** [comment]
That would be the sensible solution. The nonsensical solution would be to implement it using reduce, which is what this lib aims to provide.

The bug should be fixed in v0.15.1
